name: milemarker
description: A Flutter app for tracking your drives and trips
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Maps and Location
  google_maps_flutter: ^2.6.1
  geolocator: ^11.0.0
  
  # Database
  sqflite: ^2.3.2
  path: ^1.9.0
  
  # State Management
  provider: ^6.1.1
  
  # UI/UX
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10
  
  # Permissions
  permission_handler: ^11.3.0
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  
  # File handling
  path_provider: ^2.1.2
  
  # HTTP requests
  http: ^1.1.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/map_style.json
    - .env