name: milemarker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core plugins
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  intl: ^0.20.2
  url_launcher: ^6.3.1

  # Maps & geocoding
  google_maps_flutter: ^2.12.1
  geocoding: ^3.0.0

  # HTTP client
  http: ^1.3.0
  logging: ^1.0.2  # Added for application logging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
